# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkeTWK7kyODAaAy4FDN2llXA0IANCwH5
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([0, 0.1, 0.2, -0.5, 1, -0.7, 0.2, 0.1, 0, 0.05, 0])
plt.figure(figsize=(10, 4))
plt.plot(x, y, color="blue", linewidth=2)
plt.title("Yurak urishi diagrammasi (EKG)", fontsize=14)
plt.xlabel("Vaqt", fontsize=12)
plt.ylabel("Signal kuchi", fontsize=12)
plt.grid(True, linestyle="--", alpha=0.7)
plt.show()