# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkeTWK7kyODAaAy4FDN2llXA0IANCwH5
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,0,5,5])
y = np.array([0,35,35,0])
plt.scatter(x,y)
plt.show()