# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkeTWK7kyODAaAy4FDN2llXA0IANCwH5
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
mycolor = ['red', 'green', 'purple','lime','aqua','yellow']
plt.scatter(x,y, color=mycolor)
plt.show()